# Site settings
title: Metro Cebu North Force
email: info@metrocebunorthforce.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://metrocebunorthforce.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
google_analytics: UA-106150678-1

facebook: https://www.facebook.com/MetroCebuNorthForceBranchManulife/
tel: +63.32.2319177
info: info@metrocebunorthforce.com
tel2: 0995.619.3639
email2: boy_archie@manulife.com.ph

addr: Unit 101, Ground Floor Keppel Center, Samar Loop cor Cardinal Rosales Avenue, Cebu Business Park, Cebu City
gmaps_api_key: