# Site settings
title: Metro Cebu North Force
email: info@metrocebunorthforce.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://metrocebunorthforce.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
google_analytics: UA-106150678-1

facebook: https://www.facebook.com/MetroCebuNorthForceBranchManulife/
tel: +63323492495
info: info@metrocebunorthforce.com
